# First Skaffold Config
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: rcfg # runpod config
build:
  artifacts:
  - image: pipelinepilot/runpod-template-images
    context: src/images/runpod-template
    platforms: ["linux/amd64", "linux/arm64"] # MacOS M1 is arm64
    sync:
      infer:
      - '**/*.sh'
    docker:
      dockerfile: Dockerfile
  local:
    push: true
    concurrency: 0
manifests:
  rawYaml:
    - my-pod.yml
deploy:
  kubectl: {}

---

# Second Skaffold Config
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: fcfg # flyte config
build:
  artifacts:
  - image: pipelinepilot/preprocess_data
    context: src/images/flyte-task-images/preprocess_data
    docker:
      dockerfile: Dockerfile
    sync: {}
  - image: pipelinepilot/trigger_runpod
    context: src/images/flyte-task-images/trigger_runpod
    docker:
      dockerfile: Dockerfile
    sync: {}
  local:
    push: false
    concurrency: 0