apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: nerfstudio-demo
build:
  artifacts:
    - image: pipelinepilot/runpod-template-images
      sync:
        infer:
          - '**/start.sh'
      docker:
        dockerfile: Dockerfile
  local:
    push: true
manifests:
  rawYaml:
    - my-pod.yml